spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/memories
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update #??? CREATE? ???? ???.
    properties:
      hibernates:
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  header: Authorization
  secret: aW1zZW1pbmFuZHl1bWluaGVsbG90aGlzaXM2NGJpdC1pbm91cmZ1dHJlCg==YW5kZmluYWxseS1pd29uZGVybG92ZQo=
  token-validity-in-seconds: 86400
